# Generated by Django 5.0.2 on 2024-02-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_urlmodel_delete_urlshortener'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_url_created', models.BigIntegerField()),
            ],
        ),
    ]
