# Generated by Django 5.0.2 on 2024-02-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_globaldatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='GlobalDataModel',
        ),
    ]
