# Generated by Django 5.0.2 on 2024-03-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_urlcounter_delete_globaldatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
