# Generated by Django 5.0.2 on 2024-03-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_urlmodel_visit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('violation_type', models.CharField(choices=[('spam', 'Spam'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
