# Generated by Django 5.0.2 on 2024-03-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='violation_type',
            field=models.CharField(choices=[('spam', 'Spam'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('inappropriate_content', 'Inappropriate Content'), ('illegal_activities', 'Illegal Activities'), ('rights_infringement', 'Rights Infringement'), ('double_redirection', 'Double Redirection'), ('other', 'Other')], max_length=50),
        ),
    ]
